### ISSUE TITLE
Convolution vs. cross-correlation

### ISSUE THREAD

**Issue by gwtaylor** [dukebw/master-thesis-fusion#5]
What you're describing on page 2 is in fact cross-correlation and not convolution. Formally, convolution implies a 180 degree rotation of the kernel. This does not matter in the case of CNNs as long as you're consistent. But it would be worth mentioning. If you google "cross-correlation vs. convolution CNN" you will see a lot of discussion on this point. To your credit, you never actually call equation 1.2 "convolution". So maybe you already know this and deliberately avoided using that term. I still think it's worth pointing out that despite the name (and most practitioners ignoring the difference) most implementations of CNNs are using cross-correlation.

**Comment by dukebw** [comment]
I wasn't actually aware of this distinction, although I had heard that it's incorrect to call transposed convolution "deconvolution", which makes sense now. I never took a signal processing course. Thank you!
