### ISSUE TITLE
Indices in attention section, looks ok but use of t_i is weird because both are indices

### ISSUE THREAD

**Issue by gwtaylor** [dukebw/master-thesis-fusion#9]
This makes sense to me:

I interpret t to index Q and Y, i.e. t = 1.. t_1 and i to index K and V, that is, i = 1.. t_2.

But the use of t_i is weird because they're both indices. When you used t_i, I thought i is only in {1, 2} such that t_i has only two settings: t_1 (number of Q, Y vectors) and t_2 (number of K, V vectors). 

Please check to make sure the indexing is consistent.

**Comment by dukebw** [comment]
Sorry, I think here I was using t_i as you interpreted with i in {1, 2}. I reworded and split this into two sentences.
